### ISSUE TITLE
problem: doesn't work with 3.0.0b5

### ISSUE THREAD

**Issue by wesyoung** [ventz/docker-cif#1] opened 2018-02-09 20:14 UTC
https://github.com/csirtgadgets/bearded-avenger-deploymentkit/releases/tag/3.0.0b5

let me know if that works for you...

**Comment by ventz** [comment] 2018-02-09 21:40
@wesyoung 

Added ARG to Dockerfile:
```
ARG DOCKER_BUILD=yes
```

But it looks like it's not being looked at (same error as without it):

```
[WARNING]: While constructing a mapping from /tmp/bearded-avenger-
deploymentkit/roles/nginx/defaults/main.yml, line 3, column 3, found a
duplicate dict key (server_name). Using last defined value only.
 [WARNING]: While constructing a mapping from /tmp/bearded-avenger-
deploymentkit/ubuntu16/tasks/main.yml, line 2, column 3, found a duplicate dict
key (when). Using last defined value only.
statically imported: /tmp/bearded-avenger-deploymentkit/ubuntu16/tasks/main.yml

PLAYBOOK: site.yml *************************************************************
1 plays in site.yml

PLAY [configure platform] ******************************************************

TASK [configure python] ********************************************************
task path: /tmp/bearded-avenger-deploymentkit/ubuntu16/site.yml:23
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\naptitude is already the newest version (0.7.4-2ubuntu2).\npython-minimal is already the newest version (2.7.11-1).\npython-minimal set to manually installed.\n0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "aptitude is already the newest version (0.7.4-2ubuntu2).", "python-minimal is already the newest version (2.7.11-1).", "python-minimal set to manually installed.", "0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded."]}

TASK [setup] *******************************************************************
task path: /tmp/bearded-avenger-deploymentkit/ubuntu16/site.yml:26
ok: [localhost]

TASK [set store fact] **********************************************************
task path: /tmp/bearded-avenger-deploymentkit/ubuntu16/site.yml:29
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [set build_sdist] *********************************************************
task path: /tmp/bearded-avenger-deploymentkit/ubuntu16/site.yml:35
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Check for version 16.04] *************************************************
task path: /tmp/bearded-avenger-deploymentkit/ubuntu16/tasks/main.yml:2
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Must be version 16.04 or higher"}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```

That said - it seems to not be getting to the check from what I can tell?
But the weird part is that however the check is for 16.04, it's not capturing in Docker -- I am using a 16.04 container:

```
FROM ubuntu:16.04
LABEL developer="Wes Young <wes@csirtgadgets.org>"
```

**Comment by ventz** [comment] 2018-02-09 21:43
@wesyoung On docker, this file exists:
```
cat /etc/lsb-release  | grep DISTRIB_RELEASE
```

So -- the question is, how are you checking for it? :)

**Comment by wesyoung** [comment] 2018-02-16 20:07
https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/easybutton.sh#L28

reading in the vars and then jumping down into either ubuntu16/ or centos7/ and triggering bootstrap.sh

(i think that's what you're asking?)

**Comment by wesyoung** [comment] 2018-02-16 20:13
err wait, scratch that.. i mis-read the first comment- ansible is the one checking for it. you'd have to insert an ansible debug statement above the line that checks for what the version is:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ubuntu16/tasks/main.yml#L4

something like:

```
- debug: msg="{{ ansible_distribution_version }}"
```

**Comment by ventz** [comment] 2018-04-12 16:25
@wesyoung Sorry, somehow I never got an email notification about this thread update.

I saw that you released a RC1 -- would love to get this fixed before you release "stable", so that we can get docker working.

I can definitely pull the correct version from the container:
```
root@0e66e27f8b83:/# ansible localhost -m setup |grep distribution_version
        "ansible_distribution_version": "16.04",
```

If I am understanding the check that you linked (https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ubuntu16/tasks/main.yml#L4) -- I think the problem is that it's looking for a version "less than" 16.04, rather than less than or equal to.

**Comment by wesyoung** [comment] 2018-04-16 16:28
are you working out of a local branch or something? can you point to a branch you're testing with so i can try and replicate what's going on?

**Comment by ventz** [comment] 2018-04-16 17:25
This is using the latest release (3.0.0rc1) + the docker changes.


Here's the dockerfile:

```
FROM ubuntu:16.04
LABEL developer="Wes Young <wes@csirtgadgets.org>"
LABEL docker_maintainer="Ventz Petkov <ventz@vpetkov.net>"

EXPOSE 443 5000

ARG DOCKER_BUILD=yes

ENV CIF_VERSION 3.0.0rc1
ENV CIF_RUNTIME_PATH /var/lib/cif
ENV SUDO_USER root
ENV DEBIAN_FRONTEND=noninteractive

COPY supervisord.conf /usr/local/etc/supervisord.conf
COPY entrypoint /

RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections

RUN apt-get update && apt-get install -y git sudo resolvconf supervisor; \
    cd /tmp && git clone https://github.com/csirtgadgets/bearded-avenger-deploymentkit

WORKDIR /tmp/bearded-avenger-deploymentkit
# Override for Docker - don't need anything related to systemd; \
RUN git checkout tags/$CIF_VERSION ; \
    sed -i "s/- include_tasks: firewall.yml//" ubuntu16/tasks/main.yml ; \
    sed -i "s/  tags: firewall//" ubuntu16/tasks/main.yml ; \
    mkdir -p /etc/resolvconf/resolv.conf.d ; \
    # Override for Docker - don't need anything related to systemd/on-startup
    echo "---" > ubuntu16/localhost.yml; \
    echo "- name: Install bearded-avenger" >> ubuntu16/localhost.yml; \
    echo "  hosts: localhost" >> ubuntu16/localhost.yml; \
    echo "  environment:" >> ubuntu16/localhost.yml; \
    echo "    LANG: C" >> ubuntu16/localhost.yml; \
    echo "    LC_ALL: C" >> ubuntu16/localhost.yml; \
    echo "    LC_MESSAGES: C" >> ubuntu16/localhost.yml; \
    echo "  become: True" >> ubuntu16/localhost.yml; \
    echo "  roles:" >> ubuntu16/localhost.yml; \
    echo "    - { role: ubuntu16, tags: role-ubuntu16 }" >> ubuntu16/localhost.yml; \
    echo "    - { role: bearded-avenger, tags: role-bearded-avenger }" >> ubuntu16/localhost.yml; \
    cp -f test.sh /root/test.sh ; \
    ln -s /home/cif/.cif.yml /root/.cif.yml ; \
    ln -s /home/cif/.cifrc /root/.cifrc ; \
    chmod 755 /root/test.sh ; \
    chmod 755 /entrypoint ; \
    cd ubuntu16 && bash bootstrap.sh ; \
    rm -Rf ../../bearded-avenger-deploymentkit


# This has to be last/post volume dir work.
# See NOTE at: https://docs.docker.com/engine/reference/builder/#volume
VOLUME /etc/cif
VOLUME /var/log/cif
VOLUME /var/lib/cif

WORKDIR /home/cif

ENTRYPOINT ["/entrypoint", "-n"]
```

**Comment by dylanjacob** [comment] 2018-04-17 21:48
I think this has something to do with the first two sed lines after the git checkout in your docker file.
In rc2, the DOCKER_BUILD variable gets carried into ansible, and the firewall task is skipped without having to do anything else. The mechanism that sets that ansible variable is in the global_vars.yml file which I think gets pulled in from site.yml.

**Comment by dylanjacob** [comment] 2018-04-17 21:48
to further clarify, the two sed lines remove the name and tags field from the yaml, but there is still a when that is left, and gets applied to the version detection task

**Comment by ventz** [comment] 2018-04-17 21:52
@dylanjacob Correct - I had those before we added "DOCKER_BUILD" support. This is why I had proposed adding some variables for docker, because every 2-3 releases the yaml files changed, and I would have to dig through to find where stuff went/what changed/etc. This way, as stuff moves, it will be auto skipped.

Ideally, the sed lines should not be there.

The localhost.yml I think is still needed, but @wesyoung would know better about this.

**Comment by dylanjacob** [comment] 2018-04-17 21:58
@ventz now that the DOCKER_BUILD variable check is added to ubuntu16/tasks/main.yml for the firewall task and the environment variable is imported to ansible, we shouldn't need the sed lines like you said. I submitted a pull request with those changes and one additional change (sudo useradd cif)

**Comment by dylanjacob** [comment] 2018-04-17 22:26
so with pull request #3, it seems to resolve the issue with the version check, but now it's back to the issue I had submitted on the deploymentkit csirtgadgets/bearded-avenger-deploymentkit#38 😕

**Comment by ventz** [comment] 2018-04-17 23:32
Adding it here, I think this is the main problem:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/issues/40

**Comment by wesyoung** [comment] 2018-04-18 14:01
@dylanjacob i'm scratching my head over that one- it seems like either something changed, or i mis-read the doc about `service` vs `systemd`. odd cause it appears to do the right thing in non-docker land.

anyway- logged that one to take a look at:

https://github.com/csirtgadgets/cif-ansible-role/issues/3

seems like for those tasks just need to switch from using `service` to `systemd`, just not sure of the other implications of doing that. in the past we ran into some issues where the service didn't restart on boot properly.

**Comment by wesyoung** [comment] 2018-04-18 16:26
i tweaked teh role- checkout the deploymentkit master and tweak the ver of this:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ansible.sh#L14

from `0.0.7` to `0.0.8` and see if that `daemon_reload` issues doesn't go away.

**Comment by wesyoung** [comment] 2018-04-18 16:27
actually- i can just push that version tweak to master, make it simpler to test. done.

**Comment by dylanjacob** [comment] 2018-04-18 17:19
I tried this in Docker, and I _still_ get an error for the "enable services at boot" but it's a different error. Thinking about this though, do we even need to "enable services at boot" within Docker? We just need to start them when the container comes up, i.e. with entrypoint or something.

I would say we should add a DOCKER_BUILD check for csirtgadgets.cif/tasks/router/services.yml which should skip creating the systemd services and trying to enable them at boot. I can submit a pull request to csirtgadgets/cif-ansible-role if this is an acceptable approach.

Currently, the first task succeeds, but the second fails with this error:
`TASK [csirtgadgets.cif : enable services at boot] ******************************
task path: /tmp/bearded-avenger-deploymentkit/roles/csirtgadgets.cif/tasks/router/services.yml:9
failed: [localhost] (item=cif-router.service) => {"changed": false, "failed": true, "item": "cif-router.service", "msg": "failure 1 during daemon-reload: Failed to connect to bus: No such file or directory\n"}
failed: [localhost] (item=cif-httpd.service) => {"changed": false, "failed": true, "item": "cif-httpd.service", "msg": "failure 1 during daemon-reload: Failed to connect to bus: No such file or directory\n"}`

Add from @ventz - ^ agreed with @dylanjacob here.

**Comment by wesyoung** [comment] 2018-04-18 17:49
i'm not a docker expert- but i'm guessing it's missing systemd stuff based on that message (and or it's not running at the time of the build). merged the PR, will tag.

good stuff! ty!

**Comment by dylanjacob** [comment] 2018-04-18 17:52
My (weak) understanding of the systemd docker issue is that since it isn't running from /sbin/init as PID 1, the normal "bootup" process isn't followed...
I was looking into trying to get things up and running by ending the Dockerfile with `CMD ['/sbin/init']` to try and trick it into doing that more like a real box, but didn't get real far with it

**Comment by dylanjacob** [comment] 2018-04-18 18:05
@wesyoung You're probably already on top of this, but looks like Ansible still doesn't know about `csirtgadgets.cif,0.0.9`

**Comment by ventz** [comment] 2018-04-18 18:37
@dylanjacob You are correct - with docker the idea is you can run "ONE" thing as pid 1. People abuse this by launching stuff like supervisord which spawns the rest of them as threads/processes. The main reason is that you should have multiple containers. In my oppinion, in some places that makes sense, and in others it does not. This is probably a great example of where it does not make sense (again, imo anyway). You don't want to deal with 3-4 containers just because you want to demo/"try out" cifs. I think using supervisord is a good solution for this.

**Comment by ventz** [comment] 2018-04-18 20:18
Pulled the latest (due to the first 0.0.8 and then 0.0.9 change for csirtgadgets.cif) and built - the cif-router did not start, seeing:

2018-04-18 20:13:15,319 DEBG 'cif-router' stdout output:
Unable to read /etc/cif/cif-router.yml config file

and the .cif.yml is now missing from /home/cif now.

**Comment by ventz** [comment] 2018-04-18 20:20
@wesyoung See comment from @dylanjacob above (https://github.com/ventz/docker-cif/issues/1#issuecomment-382463174)

That's currently the "next" issue :)

**Comment by ventz** [comment] 2018-04-19 16:58
Closing this in favor of the "master" ticket @dylanjacob created here: https://github.com/ventz/docker-cif/issues/4

(ping @wesyoung)

**Closed as completed by ventz** 2018-04-19 16:58 UTC
